# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-doc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.47.0
        with:
          ruby-version: 2.5

      - name: Install YARDoc
        run:  gem install yard

      - name: Copy README
        run: cp README.md ione/server

      - name: Copy YARDoc conf
        run: cp docs/.yardopts ione/server
      
      - name: Generating Docs
        working-directory: ione/server
        run: yardoc

      - name: List doc
        run: ls -lh ione/server/doc

      - name: Deploy docs via FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.DOCS_FTP_DESTINATION }}
          ftp-username: ${{ secrets.DOCS_FTP_USER }}
          ftp-password: ${{ secrets.DOCS_FTP_PASSWORD }}
          local-dir: ione/server/doc
